name: Laporkan API yang bermasalah
description: Laporkan API yang mengalami masalah atau telah tidak aktif
title: "[ERROR]: "
labels: ["error", "triage"]
assignees:
  - vzrenggamani
body:
  - type: textarea
    id: situasi-user
    attributes:
      label: Apa yang terjadi?
      description: Bisakah anda menjelaskan apa yang ingin anda lakukan?
      placeholder: Ceritakan di bawah ini
      value: "Saya tidak bisa mengakses API ...., saya mengalami error....."
    validations:
      required: true
- type: input
  id: nama-api
  attributes:
    label: Nama API
    description: "Nama API yang anda gunakan"
    placeholder: "Peta Cuaca Indonesia BMKG"
  validations:
    required: true
- type: input
  id: api-endpoint
  attributes:
    label: API Endpoint
    description: "Endpoint dari API yang anda gunakan"
    placeholder: "https://data.bmkg.go.id/cuaca/peta.json"
  validations:
    required: true
- type: dropdown
    id: respon-api
    attributes:
      label: Respon dari API
      description: Bagaimana respon dari API yang anda gunakan?
      options:
        - 200 (OKE)
        - 401 Unauthorized
        - 403 Forbidden
        - 404 Not Found
        - 405 Not Acceptable
        - 429 Too many request
        - 500 Internal server error
        - 502 Bad gateway
        - 504 Service unavailable
    validations:
      required: true
  - type: textarea
    id: code
    attributes:
      label: Script / Kode Consume API
      description: Mohoncopypastekan potongan kode yang anda gunakan untuk mengambil data dari API yang dimaksud
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Log Error
      description: Mohon copypastekan error log yang anda dapat ketika menjalankan error
      render: shell
